apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/html
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: local-pvc