apiVersion: v1
kind: Pod
metadata:
  name: time-check
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/nginx
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: log-claim